{% set version = "214" %}

package:
  name: diffoscope-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diffoscope/diffoscope-{{ version }}.tar.gz
  sha256: d670774498667be9dde75b14d94f57526834fc6b1d6aff89f6c68570a2246b03

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - python-libarchive-c
    - python-magic

test:
  commands:
    - echo "tests in subpackages"

outputs:
  - name: diffoscope
    build:
      script: {{ PYTHON }} -m pip install . --no-deps -vv
      noarch: python
      entry_points:
        - diffoscope = diffoscope.main:main
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - python-libarchive-c
        - python-magic
    test:
      imports:
        - diffoscope
      requires:
        - pip
      commands:
        - python -m pip check
        - diffoscope --version | grep {{ version }}
        - diffoscope --help
        - diffoscope --list-tools
        - diffoscope --list-missing-tools

  - name: diffoscope-all-tools
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - {{ pin_subpackage("diffoscope") }}
        - argcomplete
        - binutils
        - bzip2
        - cctools
        - defusedxml
        - docx2txt
        - e2fsprogs
        - ffmpeg
        - gettext
        - ghc
        - giflib
        - gnupg
        - h5py
        - hdf5
        - imagemagick
        - jsondiff
        - libdb
        - llvmdev
        - mono
        - ocaml
        - openjdk
        - openssh
        - pdfminer.six
        - poppler
        - postgresql
        - progressbar
        - pycryptodome
        - pypdf2
        - python-debian
        - python-tlsh
        - r
        - rpm-tools
        - squashfs-tools
        - unzip
        - vim
        - wabt
        - zip
    test:
      source_files:
        - tests
      requires:
        # pip check
        - pip
        # real test deps
        - file
        - pytest
        # test extras
        - pytest-cov
      commands:
        - python -m pip check
        - diffoscope --list-missing-tools
        - |-
          pytest -vv \
            --tb=long \
            --cov=diffoscope \
            --cov-report=term-missing \
            --cov-report=term:skip-covered \
            --cov-fail-under=76 \
            --no-cov-on-fail \
            -k="not ( \
              assert_non_existing or \
              test_berkeley_db or \
              test_code_is_black_clean or \
              test_elf or \
              test_icc or \
              test_item_rdb or \
              test_macho or \
              test_rlib or \
              test_wasm or \
              test_docx or \
              (test_pdf and test_no_differences) \
            )"

about:
  home: https://diffoscope.org
  license: GPL-3.0-or-later
  summary: in-depth comparison of files, archives, and directories
  license_family: GPL
  license_file: COPYING
  description: |-
    diffoscope will try to get to the bottom of what makes files or directories
    different. It will recursively unpack archives of many kinds and transform
    various binary formats into more human readable form to compare them. It can
    compare two tarballs, ISO images, or PDF just as easily.
  dev_url: https://salsa.debian.org/reproducible-builds/diffoscope

extra:
  feedstock-name: diffoscope
  recipe-maintainers:
    - bollwyvl
